# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20171021_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes'),
            preserve_default=False,
        ),
    ]
