# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
        migrations.AddField(
            model_name='hobby',
            name='practitioners',
            field=models.ManyToManyField(related_name='users_hobbies', to='app_main.User'),
        ),
    ]
