# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='destination',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='message',
        ),
    ]
