# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20171028_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='start_date',
        ),
    ]
